image: Visual Studio 2015

environment:
    matrix:
        - nodejs_version: '14'

platform:
    - x64

install:
    # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
    - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
    - yarn
test_script:
    - yarn test
build: off
